# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_username: user
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: e8a815494daac1815fdd708c460fb326040fb6ac21e79590e4a25ded5f234941c6d1b90fae867c2b40269d38bc31aef33ed4edcd7cdc071560449661f3f06005

test:
  domain_name: example.com
  secret_key_base: d107a32619edd0019d42b823afe7d083cfa02744415c1bea2c16161938ea50d4d646574297e64522ebba7f5fee8a574c210c454e9be6806aaff20d367e5be599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_username: <%= ENV["ADMIN_USERNAME"] %>
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
